version: '3.1' #docker version

services:
  www:
    build: ./
    volumes:
      - "./:/var/www/html" #sync project dir with container web dir
    ports:
      - 80:80
      # - 443:443 #for future ssl traffic
  db:
    image: mysql:8.0.30
    # container_name: db
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=test123
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - 8888:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      
# networks:
#   default:
#       name: db-host

volumes:
  dbdata: